apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: ali-nginx-argo-application
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/alirezaghey/argocd-samples.git
    targetRevision: HEAD
    path: envs/ali
  destination:
    server: https://kubernetes.default.svc
    namespace: nginx-ali

  syncPolicy:
    syncOptions:
      - CreateNamespace=true

    automated:
      selfHeal: true
      prune: true
